### ISSUE TITLE
[Improvement] Allow domain selection when logging in

### ISSUE THREAD

**Issue by gd71** [spacys/mediathek#33]
Because it is quite frustrating having the login popup on first launch failing in loop as the country is not yet selected ;+)

**Comment by spacys** [comment]
The default domain is "de". What is the system behavior in case of a different domain, login loop with error messages?
Do you expect so see the settings page first or a domain reload/correction after the first login?

**Comment by gd71** [comment]
Yep I have login loop with error messages.
I have to cancel several times then go to config.
I think asking first to setup once the domain before login attempt is the most convenient for users (many are using a standard TV remote with the virtual keyboard)

**Comment by spacys** [comment]
Found the point, need to reinitialize some parameters and I try implement an automatic way.
I want to avoid to bother the customer with the setting page.  ;-)

**Comment by gd71** [comment]
Nice! let me know I will test if you need

**Comment by spacys** [comment]
I checked several things but Amazon is not providing the "home domain" if I try to logon e.g. on music.amazon.com. Therefore it is not possible to have an internal redirect to the right domain.
Looks like you have to enter the settings page first and need to set the right location.

**Comment by gd71** [comment]
Ok understood.
Nevertheless, as you open the input dialog for credential on first usage, maybe a yes/no question for the user to chek if domain has been correctly set, in case of no, open the settings dialog?

**Comment by spacys** [comment]
You mean a domain selection in upfront via popup or something like that? Good idea, I will check this.

**Comment by gd71** [comment]
yep, as the configuration setting already list possible domains...
The best solution would be having the select input shipped with the login input but I didn't found a way to create a custom dialog

**Comment by spacys** [comment]
Ok, lets define the dialog screen:
`Please select your country: ` - `List of domains based on supported addon domains`
`Please enter your user account name: ` - `input field`
`Please enter your password: ` - `input field`
`Ok` - `Cancel`

Then there is just one screen for all the necessary information in upfront. Should be possible to implement.

**Comment by spacys** [comment]
Feature implemented with #38
