### ISSUE TITLE
I can log in but can’t browse anything

### ISSUE THREAD

**Issue by Jaythe2nd** [spacys/mediathek#37]
After I log in to my amazon account I get the list of categories (albums, playlists..), but whichever I choose I get an error “check log files.”
I uploaded the log file if that helps. Thanks.
https://paste.kodi.tv/amutumacim

**Comment by spacys** [comment]
Please go to addon settings and click on `Reset Addon`, double check the domain entry afterwards and then `Ok`. You have to select the right one for your country and try again.

**Comment by Jaythe2nd** [comment]
I did choose the right one (US) before launching the addon and logging in

**Comment by spacys** [comment]
Could you please enter the addon settings again and click on `Activate Logging`, restart Kodi, navigate to the point which you want to see and stop everything. Post the log file and deactivate the Addon Logging.

**Comment by Jaythe2nd** [comment]
https://paste.kodi.tv/uvacapenel

**Comment by spacys** [comment]
Interesting, the requsted page is not available for domain *.com
Could you please do the same for ` New Playlists`, `Purchased Albums` and menu entry `New Recommendations`?

**Comment by Jaythe2nd** [comment]
https://paste.kodi.tv/ropiguviye

**Comment by spacys** [comment]
Looks like I have to remove the US support for the time being.
All interfaces are not available for `music.amazon.com`. So Amazon has a different setup for Europe and US. I didn't expect this and unfortunately I cannot check the `music.amazon.com` page due to automatic redirects. Sorry for that.

**Comment by Jaythe2nd** [comment]
You can use a vpn to set your location to US. Anyway thanks and hopefully you’ll be able to fix it soon.

**Comment by spacys** [comment]
Readme was updated and the issue can considered in the future.
