### ISSUE TITLE
Way to provide pull requests

### ISSUE THREAD

**Issue by gd71** [spacys/mediathek#6]
Hello,
Having the addon in zip format does not help for pull requests :/
Would be nice to have kind of source code tree like:
  - plugin.audio. amazonmedia  <=contain source tree
  - repository                              <= contain zip files for each version

**Comment by spacys** [comment]
Good idea, let me check how to do this.

**Comment by spacys** [comment]
I added two new folders to avoid any disruptions:
1. zip -> to store all the zip files
2. source -> to store all the details

Please check if you are now able to work with.

**Comment by gd71** [comment]
will have a look this week-end but look fine
thanks

**Comment by gd71** [comment]
looks good,
will prepare a pull request for french user and translation in a dedicated branch hopefully this week.
BTW : in your license challenge you are using urllib.quote which is not compatible with python 3
not sure on how you want to manage this issue, I prefer let you fix this one

**Comment by gd71** [comment]
It's fine,
would you prefer pull requests on "feature" branch ?
make sure you configured default branch for pull request and maybe branch protection option if needed

**Comment by spacys** [comment]
Will do so, need to check how to do this.

**Comment by gd71** [comment]
learning github too, so I may be wrong but looks to me the way to do so.
Whatever you will propose is fine to me
