### ISSUE TITLE
Doesn't work on RaspberryPi

### ISSUE THREAD

**Issue by Nicko98** [spacys/mediathek#76]
Hi,
for Raspberry Pi there is no Kodi 19 as far as I know. Since this AddOn needs xbmc.python 3.0.0 which is not part of Kodi 18 I cant get this running. Is there an easy way to port this back to xbmc.python 2.X.X? Would love to use your addon!

**Comment by spacys** [comment]
There is a [version for Kodi 18](https://github.com/spacys/mediathek/blob/master/plugin.audio.amazonmedia/plugin.audio.amazonmedia-0.2.2.zip) available, but this version is not updated nor fixed. It is just for historical reasons available. So please expect logon issues if you try to use it.

**Comment by spacys** [comment]
[Kodi 19 is available for Raspi](https://kodi.tv/download/853), please try again.

**Comment by Nicko98** [comment]
Thanks, I think I’ll have a look on tuesday.

**Comment by spacys** [comment]
Do you have any updates for me and/or can I close this issue?
