### ISSUE TITLE
Error: Logon was not possible

### ISSUE THREAD

**Issue by luckylukz02** [spacys/mediathek#78]
Selected UK as domain identifier.

Username and password proven to be correct.

Running Kodi 20 ALPHA1 (particular reason) but same issue replicated on Kodi 19.

Log:
https://paste.kodi.tv/ikudoqepik.kodi

**Comment by spacys** [comment]
new version is available, please try again

**Comment by luckylukz02** [comment]
Great news. How long does it take to appear in the repository? Still showing 1.0.10 in my kodi.

**Comment by luckylukz02** [comment]
Same issue continues after update to 1.0.11

Again replicated in Kodi 19 as well.

Log:
Removed

**Comment by spacys** [comment]
Please do not create any debug logs with keyboard scancodes and change your Amazon password, just for security reason.
Back to the issue, disable the Kodi debug log - I do not need it - , move to the addon settings and click on "reset addon". Select your country code and activate the advanced logging from this addon, Ok and try again.
If this will not help close Kodi, try to remove the folders `/.kodi/userdata/addon_data/plugin.audio.amazonmedia` and `/.kodi/addons/plugin.audio.amazonmedia/resources/lib/__pycache__`. Start Kodi again, open the addon settings set your country code and activate the advanced settings.

**Comment by luckylukz02** [comment]
> Please do not create any debug logs with keyboard scancodes and change your Amazon password, just for security reason.
> Back to the issue, disable the Kodi debug log - I do not need it - , move to the addon settings and click on "reset addon". Select your country code and activate the advanced logging from this addon, Ok and try again.
> If this will not help close Kodi, try to remove the folders `/.kodi/userdata/addon_data/plugin.audio.amazonmedia` and `/.kodi/addons/plugin.audio.amazonmedia/resources/lib/__pycache__`. Start Kodi again, open the addon settings set your country code and activate the advanced settings.

Did as instructed still same error.

**Comment by spacys** [comment]
Hm..please share this advanced addon log

**Comment by luckylukz02** [comment]
Where do I find this log?

Thanks

**Comment by spacys** [comment]
this is the 'normal' Kodi log, but then with more details from my addon

**Comment by luckylukz02** [comment]
Was not able to create a log without enabling kodi debug logging

Suppressed my password

Also tried disabling two factor auth on amazon account first

Log:
https://paste.kodi.tv/dofajikake.kodi

**Comment by luckylukz02** [comment]
After disabling two factor authentication on amazon account and resetting the addon I was able to login successfully. 

Started receiving notification from amazon to approve the login which allowed the login finally.

However whenever I try to play a particular song I get a 'Playback failed' error.

Log:

https://paste.kodi.tv/divesunopo.kodi

**Comment by spacys** [comment]
Looks the MFA is not proper working, need to check it. But good to hear, finally the logon was possible.
If you go to the addon settings and enable `Activate Logging`, this addon will add some log entries to the default Kodi log, there is nothing else to do...then you will see entries starting with `[Amazon Media]`.
In your last log is nothing visible in regards to addon execution or playback issues. Would be good if you can share a new log.

**Comment by luckylukz02** [comment]
Hopefully something in here useful

Log:
https://paste.kodi.tv/exuyidosit.kodi

**Comment by spacys** [comment]
Looks like there is something wrong with the widevine library: `ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)`
If not available try to install `InputStream Helper` and reinstall this library.

**Comment by luckylukz02** [comment]
> Looks like there is something wrong with the widevine library: `ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)`
> If not available try to install `InputStream Helper` and reinstall this library.

I tried (re)install Windevine CDM library... In InputStream  Helper and this fixed the playback issue.

Thanks for your work and continued support.

**Comment by spacys** [comment]
Welcome. I'll close this ticket now.
