### ISSUE TITLE
Usage in Sweden is not possible

### ISSUE THREAD

**Issue by spacys** [spacys/mediathek#94]
1.Input credentials does not save. All interaction asked me to input credentials. 
2.Can't play anything!
3. When doing a search (after I input credentials) nothing happens.
4. Trying from Yatse and directly from vim3

coreELEC 19.4 (fresh install)
Vim3 Pro

The app works in Sweden(geo)

I'm new at test feedback so let me know how, and il help you the best I can
Fritz/Sweden

_Originally posted by @RosensRauk in https://github.com/spacys/mediathek/issues/92#issuecomment-1073114819_

**Comment by spacys** [comment]
@RosensRauk, unfortunately Swedish is currently not supported, but you can help to make this possible.
First of all I need the Amazon Prime Music URL. It looks you have something else than `music.amazon.se`.

**Comment by RosensRauk** [comment]
Okey. Was looking for requirements and limitations on GitHub but must have
missed it.

Which URL do you mean? Amazon's UI is not the most intuitive.

Amazon have released their services in Sweden BUT can't use a simple URL.
They do not have a store in Sweden.
Amazon Music Premium is probably the most troublesome service I have come
across, from start to finish. I can not start the membership directly in
the app on the mobile or computer, but must go through the browser and my
Amazon account to activate the subscription. I then have to choose which
global business the Music account is to be linked to, which can therefore
not be Sweden, despite the recent launch of the Swedish site.

Tell me exactly how I can be of assistance.


Den sön 20 mars 2022 11:48spacys ***@***.***> skrev:

**Comment by spacys** [comment]
You are right, the limitations are not visible. I'll update the content.
What I meant, your local Amazon site should be `https://www.amazon.se` and therefore the local "Amazon Prime Music" site should be `https://music.amazon.se` but this site is not available.
The main question is, is "Amazon Prime Music" general available in Sweden at the moment and if so under which URL is it accessible.
