### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by ValaryS1972** [spacys/mediathek#95]
I got an error message during login. If I got right form other login issues, I've read here, it can be because of wrong domain name. If my account in USA what domain I should choose?

**Comment by PROVRS** [comment]
Hi. I have same issue with wrong login.
I'm using https://music.amazon.com/ to login from web and it works. It is not DE UK ES domain.

**Comment by spacys** [comment]
If you are familiar with few code changes, you can try the following:
- open the file `tools.py` and add to the line `self.G['TLDlist']       = ['de', 'fr', 'co.uk', 'it', 'es']` 'your' domain to the end
- open the file `settings.xml` and add to the line `<setting id="userTLD" type="enum" label="30101" values="DE|FR|UK|IT|ES" default="0"/>` 'your' domain to the end

With this small change you should be able to select the US domain in the Addon settings and the logon should work.
But please keep in mind, I identified a different API behavior for the US domain in the past. Even if you are able to logon, it could be possible the addon will not work as expected. But it is worth to try it.
