### ISSUE TITLE
can you make a version that supports the new python 3 addons 

### ISSUE THREAD

**Issue by Cxsmo-ai** [spacys/mediathek#96]
can you make a version that supports the new python 3 addons

**Comment by spacys** [comment]
What do you mean with that? This addon is for python 3. What is missing or what should I change?

**Comment by Cxsmo-ai** [comment]
then how do you get it to work

**Comment by spacys** [comment]
The question is, what issues are you facing? A bit more details would be great.
The necessary steps are described on the main page. Maybe in addition I can highlight to install inputstream helper and add with this addon the widevine library.

**Comment by Cxsmo-ai** [comment]
yes i need help installing the widevine and stuff and how to add account

**Comment by Cxsmo-ai** [comment]
and also the login keeps failing even though its 100% correct

**Comment by spacys** [comment]
Search for "kodi inputstreamhelper install" and you will find all necessary tips with your search machine of choice.
As it is installed, execute the script and "(Re)install Widevine".
Start my addon, logon process will follow. Remember, you need to have at least an Amazon Prime Account.

**Comment by Cxsmo-ai** [comment]
is there a way to do this without amazon prime and just with amazon music unlimited

**Comment by spacys** [comment]
[Account Definition](https://www.amazon.com/gp/help/customer/display.html?nodeId=GW3PHAUCZM8L7W9L)
I hope this clarifies your question and will close this ticket now.

**Comment by Pickymarker** [comment]
so does this work with amazon music unlimited but i can't get it to work but i thought amazon music unlimited is just a better prime music

**Comment by Pickymarker** [comment]
and also i'm trying to login in with a us amazon music unlimited account
