### ISSUE TITLE
How do you login with a US account

### ISSUE THREAD

**Issue by Cxsmo-ai** [spacys/mediathek#97]
How do you login with a US account

**Comment by spacys** [comment]
The way how to add different domains is described [here](https://github.com/spacys/mediathek/issues/98#issuecomment-1272355207).
Experience from the past was the Amazon US has different API's. It might still not work after this change.

**Comment by Cxsmo-ai** [comment]
so would i put us instead of pl or what because i followed that and it won't let me login 
![image](https://user-images.githubusercontent.com/74084396/194724195-786fbe78-e1aa-4684-a9e3-f4cf0f0ca30e.png)
can you just send me the tools.py and settings.xml stuff i have to change for it to work for usa account instead of telling me to look at this one that's not for usa and figure out how to make it work

**Comment by spacys** [comment]
I've already described what you have to do, just add instead of 'pl' the Amazon US expression 'com'. If you are still not able to logon, then the US API is different to the European one.
